//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorneoTenis.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TorneoTenis.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} {1}.
        /// </summary>
        public static string APELLIDO_NOMBRE {
            get {
                return ResourceManager.GetString("APELLIDO_NOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Helpers.
        /// </summary>
        public static string Helpers {
            get {
                return ResourceManager.GetString("Helpers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a jugadores.json.
        /// </summary>
        public static string Jugadores_Punto_Json {
            get {
                return ResourceManager.GetString("Jugadores_Punto_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de jugadores debe ser potencia de 2..
        /// </summary>
        public static string MESSAGES_ERROR_CANTIDAD_JUGADORES_POTENCIA_DE_2 {
            get {
                return ResourceManager.GetString("MESSAGES_ERROR_CANTIDAD_JUGADORES_POTENCIA_DE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La lista de jugadores no puede estar vacía..
        /// </summary>
        public static string MESSAGES_ERROR_LISTA_JUGADORES_VACIA {
            get {
                return ResourceManager.GetString("MESSAGES_ERROR_LISTA_JUGADORES_VACIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el archivo en la ruta: {0}..
        /// </summary>
        public static string MESSAGES_ERROR_NO_SE_ENCONTRO_EL_ARCHIVO_JSON {
            get {
                return ResourceManager.GetString("MESSAGES_ERROR_NO_SE_ENCONTRO_EL_ARCHIVO_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se requieren 2 jugadores..
        /// </summary>
        public static string MESSAGES_ERROR_SE_REQUIEREN_2_JUGADORES {
            get {
                return ResourceManager.GetString("MESSAGES_ERROR_SE_REQUIEREN_2_JUGADORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El torneo aún no comenzo..
        /// </summary>
        public static string MESSAGES_ERROR_TONEO_AUN_NO_COMENZO {
            get {
                return ResourceManager.GetString("MESSAGES_ERROR_TONEO_AUN_NO_COMENZO", resourceCulture);
            }
        }
    }
}
